### ISSUE TITLE
HomePage設計

### ISSUE THREAD

**Issue by bestian** [unischool/knowledge-base-frontend#24]
Homepage要放什麼內容呢? 

- [ ] Search bar?
- [ ] 簡介和Learn More按鈕?

<img width="879" alt="至青宇宙學校知識庫" src="https://github.com/user-attachments/assets/3878b966-3c86-4534-af04-50b21dad5864" />

**Comment by leechiuhui** [comment]
<img width="1512" alt="截圖 2024-12-26 清晨7 38 20" src="https://github.com/user-attachments/assets/64183838-db1a-4fa6-8a77-ffa4f97f3eed" />
