### ISSUE TITLE
創建profile page?

### ISSUE THREAD

**Issue by bestian** [unischool/knowledge-base-frontend#38]
@leechiuhui 請問有需要創建profile page嗎?
如果要的話，裡面要讓使用者填什麼資料呢？

**Comment by leechiuhui** [comment]
> @leechiuhui 請問有需要創建profile page嗎? 如果要的話，裡面要讓使用者填什麼資料呢？

我想應該不需要profile page，因為只有工作人員在進入後台管理系統時才需要登入（Login）。🙏
