### ISSUE TITLE
用Axios抓取資料

### ISSUE THREAD

**Issue by leechiuhui** [unischool/knowledge-base-frontend#7]
- [x] 安裝axios
- [x]  從[[https://knowledge-base-backend.leechiuhui.workers.dev/api/Courses](https://knowledge-base-backend.leechiuhui.workers.dev/api/Courses)的 D1 抓取資料(要加裝D1)
- [ ]  呈現資料

**Comment by bestian** [comment]
可以看一下console上有沒有什麼Error. 說不定是CORS的問題?

**Comment by bestian** [comment]
剛試跑了一下，看了console. 果然是CORS的問題

about:1 Access to XMLHttpRequest at 'https://knowledge-base-backend.leechiuhui.workers.dev/api/Courses' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.


但是我在knowledge-base-backend的程式碼中查不到處理
https://knowledge-base-backend.leechiuhui.workers.dev/api/Courses
的相關代碼

因此無法debug.

**Comment by leechiuhui** [comment]
> 剛試跑了一下，看了console. 果然是CORS的問題
> 
> 
但是我在knowledge-base-backend的程式碼中查不到處理
> 
> https://knowledge-base-backend.leechiuhui.workers.dev/api/Courses
> 
> 的相關代碼

請問：這個相關代碼指的是寫在cloudflare.com 裡worker中的代碼程式嗎？ 如果是，目前權限應該是可以看到的？

**Comment by bestian** [comment]
@leechiuhui 
cloudflare.com上的可以看到，
但是和Github上抓到的最近版本不同，猜想是您最後一次更動忘了push上Github。

我應該要編輯的是Github上的版本，才能有版本記錄~

**Comment by bestian** [comment]
@leechiuhui 
我先把原本的請求都加上CORS標頭。等11/11之後再merge吧。
https://github.com/unischool/knowledge-base-backend/issues/16

**Comment by bestian** [comment]
![image](https://github.com/user-attachments/assets/53f7cd1b-5a17-4bd2-bbca-96e2652c1189)

**Comment by bestian** [comment]
![image](https://github.com/user-attachments/assets/b965cbab-204f-425c-ab5b-bcdbeb64a46f)

**Comment by leechiuhui** [comment]
20241111 請ChatGpt教我index.ts程式碼內容：https://chatgpt.com/share/673229fb-cd80-8009-968c-c829b7efa055
